# Generated by Django 3.1.6 on 2021-03-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bidding_category_comments_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.FloatField(max_length=2),
        ),
    ]
