# Generated by Django 3.1.6 on 2021-03-09 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210307_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('comment', models.TextField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='title',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listed',
        ),
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.TextField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid',
            field=models.FloatField(max_length=7),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.listing'),
        ),
    ]
